version: '3.7'

services:

    redis-1:
        build:
            context: ../config
            dockerfile: Dockerfile
        container_name: redis-1
        volumes:
            - redis-data:/data
        ports:
          - "7001:6379"
        restart: always

volumes:
    redis-data:
        driver: local
        driver_opts:
            mountpoint: /app/redis/data-{{.Task.Slot}}