version: '3.7'

services:

    redis-7001:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 7001.conf
        image: eport-redis-7001
        container_name: redis-7001
        networks:
            - database
        volumes:
            - "/app/redis/7001:/data"
        ports:
          - "7001:6379"
          - "17001:16379"
        restart: always

    redis-7002:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 7002.conf
        image: eport-redis-7002
        container_name: redis-7002
        networks:
            - database
        volumes:
            - "/app/redis/7002:/data"
        ports:
          - "7002:6379"
          - "17002:16379"
        restart: always

    redis-7003:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 7003.conf
        image: eport-redis-7003
        container_name: redis-7003
        networks:
            - database
        volumes:
            - "/app/redis/7003:/data"
        ports:
          - "7003:6379"
          - "17003:16379"
        restart: always

    redis-7004:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 7004.conf
        image: eport-redis-7004
        container_name: redis-7004
        networks:
            - database
        volumes:
            - "/app/redis/7004:/data"
        ports:
          - "7004:6379"
          - "17004:16379"
        restart: always

    redis-7005:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 7005.conf
        image: eport-redis-7005
        container_name: redis-7005
        networks:
            - database
        volumes:
            - "/app/redis/7005:/data"
        ports:
          - "7005:6379"
          - "17005:16379"
        restart: always

    redis-7006:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 7006.conf
        image: eport-redis-7006
        container_name: redis-7006
        networks:
            - database
        volumes:
            - "/app/redis/7006:/data"
        ports:
          - "7006:6379"
          - "17006:16379"
        restart: always

    redis-7007:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 7007.conf
        image: eport-redis-7007
        container_name: redis-7007
        networks:
            - database
        volumes:
            - "/app/redis/7007:/data"
        ports:
          - "7007:6379"
          - "17007:16379"
        restart: always        

    redis-7008:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 7008.conf
        image: eport-redis-7008
        container_name: redis-7008
        networks:
            - database
        volumes:
            - "/app/redis/7008:/data"
        ports:
          - "7008:6379"
          - "17008:16379"
        restart: always

    redis-7009:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 7009.conf
        image: eport-redis-7009
        container_name: redis-7009
        networks:
            - database
        volumes:
            - "/app/redis/7009:/data"
        ports:
          - "7009:6379"
          - "17009:16379"
        restart: always

networks:
  database:
    driver: bridge
    name: net_database