version: "3.7"

services:

    master:
        build:
            context: ./config/master
            dockerfile: Dockerfile
        # container_name: redis-master
        volumes:
            - /app/redis/data:/data
        # ports:
        #   - "7000:6379"
        restart: always
        

    # redis-slave:
    #     image: redis
    #     container_name: slave-redis
    #     depends_on:
    #         - redis-master
    #     environment:
    #         REDIS_REPLICATION_MODE: "slave"
    #         REDIS_MASTER_HOST: redis-master
    #         REDIS_MASTER_PORT_NUMBER: 6379
    #         REDIS_MASTER_PASSWORD: "@eport2019"
    #         REDIS_PASSWORD: "@eport2019"
    #     restart: always
