version: "3.7"

services:

    master-1:
        build:
            context: ./config/master-1
            dockerfile: Dockerfile
        container_name: redis-master-1
        volumes:
            - /app/redis/data:/data
        ports:
          - "7001:6379"
        restart: always
 
    # master-2:
    #     build:
    #         context: ./config/master-2
    #         dockerfile: Dockerfile
    #     container_name: redis-master-2
    #     volumes:
    #         - /app/redis/data:/data
    #     ports:
    #       - "7002:6379"
    #     restart: always
                
    # master-3:
    #     build:
    #         context: ./config/master-3
    #         dockerfile: Dockerfile
    #     container_name: redis-master-3
    #     volumes:
    #         - /app/redis/data:/data
    #     ports:
    #       - "7003:6379"
    #     restart: always
        
    # redis-slave:
    #     image: redis
    #     container_name: slave-redis
    #     depends_on:
    #         - redis-master
    #     environment:
    #         REDIS_REPLICATION_MODE: "slave"
    #         REDIS_MASTER_HOST: redis-master
    #         REDIS_MASTER_PORT_NUMBER: 6379
    #         REDIS_MASTER_PASSWORD: "@eport2019"
    #         REDIS_PASSWORD: "@eport2019"
    #     restart: always
