version: '3.7'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        image: eport-redis-api
        environment: 
            - ASPNETCORE_ENVIRONMENT: Production
        ports:
            - "8000:80"
        restart: always