version: '3.7'

services:
    api:
        image: eport-redis-api
        ports:
            - "8001:8001"
        environment: 
            - ASPNETCORE_ENVIRONMENT: Production
        deploy:
            mode: replicated
            replicas: 3
            restart_policy:
                condition: any
    nginx:
        image: eport-redis-nginx
        depends_on:
            - api
        volumes:
            - /app/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        ports:
          - "8001:80"
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any

