version: '3.7'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        image: snp-redis-api
        container_name: eport-redis-api
        environment: 
            ASPNETCORE_ENVIRONMENT: Production
        networks: 
            - database
        ports:
            - "8000:80"
        restart: always

networks:
    database:
        driver: bridge
        name: snp_redis_network