version: '3.7'

services:

    redis-6001:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 6001.conf
        image: eport-redis-6001
        container_name: redis-6001
        networks:
            - database
        volumes:
            - "/app/redis/6001:/data"
        restart: always

    redis-6002:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 6002.conf
        image: eport-redis-6002
        container_name: redis-6002
        networks:
            - database
        volumes:
            - "/app/redis/6002:/data"
        restart: always

    redis-6003:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 6003.conf
        image: eport-redis-6003
        container_name: redis-6003
        networks:
            - database
        volumes:
            - "/app/redis/6003:/data"
        restart: always

    redis-6004:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 6004.conf
        image: eport-redis-6004
        container_name: redis-6004
        networks:
            - database
        volumes:
            - "/app/redis/6004:/data"
        restart: always

    redis-6005:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 6005.conf
        image: eport-redis-6005
        container_name: redis-6005
        networks:
            - database
        volumes:
            - "/app/redis/6005:/data"
        restart: always

    redis-6006:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 6006.conf
        image: eport-redis-6006
        container_name: redis-6006
        networks:
            - database
        volumes:
            - "/app/redis/6006:/data"
        restart: always

    redis-6007:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 6007.conf
        image: eport-redis-6007
        container_name: redis-6007
        networks:
            - database
        volumes:
            - "/app/redis/6007:/data"
        restart: always        

    redis-6008:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 6008.conf
        image: eport-redis-6008
        container_name: redis-6008
        networks:
            - database
        volumes:
            - "/app/redis/6008:/data"
        restart: always

    redis-6009:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 6009.conf
        image: eport-redis-6009
        container_name: redis-6009
        networks:
            - database
        volumes:
            - "/app/redis/6009:/data"
        restart: always

networks:
  database:
    driver: bridge
    name: eport_redis_network