version: '3.7'

services:

    redis-7001:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 7001.conf
        image: eport-redis-7001
        networks:
            - database
        volumes:
            - "/app/redis/7001:/data"
        ports:
          - "6001:6379"
        restart: always

    redis-7002:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 7002.conf
        image: eport-redis-7002
        networks:
            - database
        volumes:
            - "/app/redis/7002:/data"
        ports:
          - "6002:6379"
        restart: always

    redis-7003:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 7003.conf
        image: eport-redis-7003
        networks:
            - database
        volumes:
            - "/app/redis/7003:/data"
        ports:
          - "6003:6379"
        restart: always

    redis-7004:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 7004.conf
        image: eport-redis-7004
        networks:
            - database
        volumes:
            - "/app/redis/7004:/data"
        ports:
          - "6004:6379"
        restart: always

    redis-7005:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 7005.conf
        image: eport-redis-7005
        networks:
            - database
        volumes:
            - "/app/redis/7005:/data"
        ports:
          - "6005:6379"
        restart: always

    redis-7006:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                FILECONF: 7006.conf
        image: eport-redis-7006
        networks:
            - database
        volumes:
            - "/app/redis/7006:/data"
        ports:
          - "6006:6379"
        restart: always

networks:
  database:
    driver: bridge
    name: net_database_redis