version: '3.7'

#DON'T WORK

services:

    redis:
        build:
            context: ../config
            dockerfile: Dockerfile
        container_name: redis
        volumes:
            - redis-data:/data
        ports:
          - "7000:6379"
        restart: always

volumes:
    redis-data:
        driver: local
        driver_opts:
            device: ":/app/redis/data"