version: '3.7'


services:

    redis-1:
        build:
            context: redis
            dockerfile: Dockerfile
        container_name: redis-1
        volumes:
            - data-1:/data
        ports:
          - "7001:6379"
        restart: always
    
    redis-2:
        build:
            context: redis
            dockerfile: Dockerfile
        container_name: redis-2
        volumes:
            - data-2:/data
        ports:
          - "7002:6379"
        restart: always

    redis-3:
        build:
            context: redis
            dockerfile: Dockerfile
        container_name: redis-3
        volumes:
            - data-3:/data
        ports:
          - "7003:6379"
        restart: always

    redis-4:
        build:
            context: redis
            dockerfile: Dockerfile
        container_name: redis-4
        volumes:
            - data-4:/data
        ports:
          - "7004:6379"
        restart: always

    redis-5:
        build:
            context: redis
            dockerfile: Dockerfile
        container_name: redis-5
        volumes:
            - data-5:/data
        ports:
          - "7005:6379"
        restart: always

    redis-6:
        build:
            context: redis
            dockerfile: Dockerfile
        container_name: redis-6
        volumes:
            - data-6:/data
        ports:
          - "7006:6379"
        restart: always

volumes:
    data-1:
        name: app/redis/data1
    data-2:
        name: app/redis/data2
    data-3:
        name: app/redis/data3
    data-4:
        name: app/redis/data4
    data-5:
        name: app/redis/data5
    data-6:
        name: app/redis/data6

####----OK
# version: '3.7'

# services:

#     redis:
#         image: config_redis
#         volumes:
#             - redisVol:/data
#         ports:
#             - 7001-7009:6379
#         deploy:
#             mode: replicated
#             replicas: 9
#         restart: always

#     # sentinel:
#     #     build:
#     #         context: ./sentinel
#     #         dockerfile: Dockerfile
#     #     environment:
#     #         - SENTINEL_DOWN_AFTER=5000
#     #         - SENTINEL_FAILOVER=5000
#     #     depends_on:
#     #         - redis

# volumes:
#     redisVol:
#         name: 'app/redis/data-{{.Task.Slot}}'