version: '3.7'

services:

    redis:
        image: config_redis
        volumes:
            - app/redis/data:/data
        ports:
            - 7000:6379
        # deploy:
        #     mode: replicated
        #     replicas: 1
        restart: always

    # sentinel:
    #     build:
    #         context: ./sentinel
    #         dockerfile: Dockerfile
    #     environment:
    #         - SENTINEL_DOWN_AFTER=5000
    #         - SENTINEL_FAILOVER=5000
    #     depends_on:
    #         - redis

# volumes:
#     redisVol:
#         name: 'app/redis/data-{{.Task.Slot}}'