version: '3.7'


services:

    redis-1:
        build:
            context: redis
            dockerfile: Dockerfile
        container_name: redis-1
        volumes:
            - "app/redis/data-1":/data
        ports:
          - "7001:6379"
        restart: always
    
volumes:
    data-1: