version: '3.7'

services:

    redis:
        image: redis
        volumes:
            - app/redis/data:/data
        ports:
            - 7000:6379
        deploy:
            mode: replicated
            replicas: 9
        restart: always




#OK
# version: '3.7'

# services:

#     redis:
#         image: config_redis
#         volumes:
#             - app/redis/data:/data
#         ports:
#             - 7000:6379
#         # deploy:
#         #     mode: replicated
#         #     replicas: 1
#         restart: always

# # volumes:
# #     redisVol:
# #         name: 'app/redis/data-{{.Task.Slot}}'