version: "3.7"

services:

    redis:
        build:
            context: ./redis
            dockerfile: Dockerfile
        volumes:
            - redisVolume:/data
        ports:
            - "7001-7009:6379"
        restart: always

    # sentinel:
    #     build:
    #         context: ./sentinel
    #         dockerfile: Dockerfile
    #     environment:
    #         - SENTINEL_DOWN_AFTER=5000
    #         - SENTINEL_FAILOVER=5000
    #     depends_on:
    #         - redis


    volumes:
        redisVolume:
            external:
                name: 'app/redis/data/{{.Task.Slot}}'
