version: "3.7"

services:

    redis:
        build:
            context: ./redis
            dockerfile: Dockerfile
        container_name: "redis-{{.Task.Slot}}"
        # volumes:
        #     - "app/redis/data/{{.Task.Slot}}:/data"
        ports:
            - "7001-7009:6379"
        restart: always

    # sentinel:
    #     build:
    #         context: ./sentinel
    #         dockerfile: Dockerfile
    #     environment:
    #         - SENTINEL_DOWN_AFTER=5000
    #         - SENTINEL_FAILOVER=5000
    #     depends_on:
    #         - redis