version: '3.7'

services:

    redis:
        image: config_redis
        volumes:
            - redisVol:/data
        ports:
            - 7000:6379
        deploy:
            mode: replicated
            replicas: 9
        restart: always

    # sentinel:
    #     build:
    #         context: ./sentinel
    #         dockerfile: Dockerfile
    #     environment:
    #         - SENTINEL_DOWN_AFTER=5000
    #         - SENTINEL_FAILOVER=5000
    #     depends_on:
    #         - redis

    volumes:
        redisVol:
            external:
                name: 'app/redis/data-{{.Task.Slot}}'